# Generated by Django 2.0.2 on 2018-02-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex. Money', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(help_text='Ex. Travel', max_length=50)),
                ('spanish_word', models.CharField(help_text='Ex. Viajar', max_length=50)),
                ('spanish_pronunciation', models.CharField(blank=True, help_text='Ex. trável (puedes usar las tildes para acentuar donde se hace el énfasis en la pronunciación)', max_length=100, null=True)),
                ('phonetics', models.CharField(blank=True, help_text='Ex. /ˈtræv(ə)l/', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Ex. Suele usarse como verbo, rara como sustantivo o adjetivo', max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Category')),
            ],
        ),
    ]
